// Mocks generated by Mockito 5.4.4 from annotations
// in landscape_plant_catalog/test/features/plant_catalog/services/plant_catalog_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:hive_flutter/hive_flutter.dart' as _i3;
import 'package:landscape_plant_catalog/core/services/api_service.dart' as _i2;
import 'package:landscape_plant_catalog/core/services/storage_service.dart'
    as _i6;
import 'package:landscape_plant_catalog/features/plant_catalog/services/compatibility_engine.dart'
    as _i4;
import 'package:landscape_plant_catalog/models/care_reminder.dart' as _i8;
import 'package:landscape_plant_catalog/models/client_garden.dart' as _i7;
import 'package:landscape_plant_catalog/models/plant.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_1<E> extends _i1.SmartFake implements _i3.Box<E> {
  _FakeBox_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompatibilityResult_2 extends _i1.SmartFake
    implements _i4.CompatibilityResult {
  _FakeCompatibilityResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlantCombinationAnalysis_3 extends _i1.SmartFake
    implements _i4.PlantCombinationAnalysis {
  _FakePlantCombinationAnalysis_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  void setAuthToken(
    String? token, {
    String? refreshToken,
    _i2.UserRole? role,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
          {
            #refreshToken: refreshToken,
            #role: role,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAuthToken() => super.noSuchMethod(
        Invocation.method(
          #clearAuthToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.AuthResult> authenticate(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [username],
        ),
        returnValue: _i5.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #authenticate,
            [username],
          ),
        )),
      ) as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<void> refreshAuthToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshAuthToken,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> get(String? endpoint) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> post(
    String? endpoint,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            endpoint,
            data,
          ],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> put(
    String? endpoint,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            endpoint,
            data,
          ],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> delete(String? endpoint) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> uploadFile(
    String? endpoint,
    String? filePath,
    String? fieldName, {
    Map<String, String>? additionalFields,
    dynamic Function(
      int,
      int,
    )? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            endpoint,
            filePath,
            fieldName,
          ],
          {
            #additionalFields: additionalFields,
            #onProgress: onProgress,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> uploadMultipleFiles(
    String? endpoint,
    Map<String, String>? filePaths, {
    Map<String, String>? additionalFields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMultipleFiles,
          [
            endpoint,
            filePaths,
          ],
          {#additionalFields: additionalFields},
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i6.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Box<dynamic> get plantsBox => (super.noSuchMethod(
        Invocation.getter(#plantsBox),
        returnValue: _FakeBox_1<dynamic>(
          this,
          Invocation.getter(#plantsBox),
        ),
      ) as _i3.Box<dynamic>);

  @override
  _i3.Box<_i7.ClientGarden> get gardensBox => (super.noSuchMethod(
        Invocation.getter(#gardensBox),
        returnValue: _FakeBox_1<_i7.ClientGarden>(
          this,
          Invocation.getter(#gardensBox),
        ),
      ) as _i3.Box<_i7.ClientGarden>);

  @override
  _i3.Box<_i8.CareReminder> get remindersBox => (super.noSuchMethod(
        Invocation.getter(#remindersBox),
        returnValue: _FakeBox_1<_i8.CareReminder>(
          this,
          Invocation.getter(#remindersBox),
        ),
      ) as _i3.Box<_i8.CareReminder>);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  _i5.Future<void> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  _i5.Future<void> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  _i5.Future<void> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> storePlant(
    String? id,
    Map<String, dynamic>? plantData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storePlant,
          [
            id,
            plantData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic>? getPlant(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getPlant,
        [id],
      )) as Map<String, dynamic>?);

  @override
  _i5.Future<void> storePlants(Map<String, Map<String, dynamic>>? plants) =>
      (super.noSuchMethod(
        Invocation.method(
          #storePlants,
          [plants],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, Map<String, dynamic>> getAllPlants() => (super.noSuchMethod(
        Invocation.method(
          #getAllPlants,
          [],
        ),
        returnValue: <String, Map<String, dynamic>>{},
      ) as Map<String, Map<String, dynamic>>);

  @override
  _i5.Future<void> storeGarden(
    String? id,
    _i7.ClientGarden? garden,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeGarden,
          [
            id,
            garden,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i7.ClientGarden? getGarden(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getGarden,
        [id],
      )) as _i7.ClientGarden?);

  @override
  _i5.Future<void> storeReminder(
    String? id,
    Map<String, dynamic>? reminderData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeReminder,
          [
            id,
            reminderData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic>? getReminder(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getReminder,
        [id],
      )) as Map<String, dynamic>?);

  @override
  List<Map<String, dynamic>> getAllReminders() => (super.noSuchMethod(
        Invocation.method(
          #getAllReminders,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  _i5.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setCacheTimestamp(String? key) => (super.noSuchMethod(
        Invocation.method(
          #setCacheTimestamp,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool isCacheValid(
    String? key,
    Duration? maxAge,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isCacheValid,
          [
            key,
            maxAge,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<String> uploadFile(
    String? filePath,
    String? folder,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            filePath,
            folder,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #uploadFile,
            [
              filePath,
              folder,
            ],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [CompatibilityEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompatibilityEngine extends _i1.Mock
    implements _i4.CompatibilityEngine {
  MockCompatibilityEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.CompatibilityResult analyzeCompatibility(
    _i10.Plant? plant1,
    _i10.Plant? plant2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeCompatibility,
          [
            plant1,
            plant2,
          ],
        ),
        returnValue: _FakeCompatibilityResult_2(
          this,
          Invocation.method(
            #analyzeCompatibility,
            [
              plant1,
              plant2,
            ],
          ),
        ),
      ) as _i4.CompatibilityResult);

  @override
  List<_i4.CompatibilityResult> findCompatiblePlants(
    _i10.Plant? targetPlant,
    List<_i10.Plant>? candidatePlants, {
    double? minCompatibilityScore = 0.6,
    int? maxResults,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCompatiblePlants,
          [
            targetPlant,
            candidatePlants,
          ],
          {
            #minCompatibilityScore: minCompatibilityScore,
            #maxResults: maxResults,
          },
        ),
        returnValue: <_i4.CompatibilityResult>[],
      ) as List<_i4.CompatibilityResult>);

  @override
  List<_i10.Plant> findGroupCompatiblePlants(
    List<_i10.Plant>? existingPlants,
    List<_i10.Plant>? candidatePlants, {
    double? minAverageScore = 0.7,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findGroupCompatiblePlants,
          [
            existingPlants,
            candidatePlants,
          ],
          {#minAverageScore: minAverageScore},
        ),
        returnValue: <_i10.Plant>[],
      ) as List<_i10.Plant>);

  @override
  _i4.PlantCombinationAnalysis analyzePlantCombination(
          List<_i10.Plant>? plants) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzePlantCombination,
          [plants],
        ),
        returnValue: _FakePlantCombinationAnalysis_3(
          this,
          Invocation.method(
            #analyzePlantCombination,
            [plants],
          ),
        ),
      ) as _i4.PlantCombinationAnalysis);
}
